#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-pcs
Version  : 1.3.3
Release  : 1
URL      : https://pecl.php.net//get/pcs-1.3.3.tgz
Source0  : https://pecl.php.net//get/pcs-1.3.3.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.0 PHP-3.01
Requires: php-pcs-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
[![Build Status](https://travis-ci.org/flaupretre/pecl-pcs.svg?branch=master)](https://travis-ci.org/flaupretre/pecl-pcs)
[![GitHub release](https://img.shields.io/github/release/flaupretre/pecl-pcs.svg)](https://pecl.php.net/package/pcs)
[![License](https://img.shields.io/badge/License-PHP-blue.svg)](http://php.net/license/3_01.txt)

%package dev
Summary: dev components for the php-pcs package.
Group: Development
Requires: php-pcs-lib = %{version}-%{release}
Provides: php-pcs-devel = %{version}-%{release}
Requires: php-pcs = %{version}-%{release}

%description dev
dev components for the php-pcs package.


%package lib
Summary: lib components for the php-pcs package.
Group: Libraries

%description lib
lib components for the php-pcs package.


%prep
%setup -q -n pcs-1.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/php/ext/pcs/client.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/pcs.so
